#!/bin/sh

INVALID_INPUT=255

# This script is a backup solution for setting up/removing MCTP endpoint for NICs
action=$1
slot=$2
# NIC bus are 24~27.
bus=$((24 + slot))
# Static EID for NIC are 90~93.
eid=$((90 + slot))

sleep 2

set_nic_eid() {
    MAX_RETRIES=3
    RETRY_COUNT=0
    while [ "$RETRY_COUNT" -lt "$MAX_RETRIES" ]; do
        busctl call xyz.openbmc_project.MCTP /xyz/openbmc_project/mctp au.com.CodeConstruct.MCTP AssignEndpointStatic sayy "mctpi2c${bus}" 1 0x32 "$eid"
        ret=$?
        if [ "$ret" -eq 0 ]; then
            break
        fi
        echo "Retry setting EID ${eid}"
        RETRY_COUNT=$((RETRY_COUNT + 1))
    done
}

if [ "$action" = "add" ]; then
    echo "Adding MCTP endpoint for slot $slot"
    set_nic_eid
elif [ "$action" = "remove" ]; then
    echo "Removing MCTP endpoint for slot $slot"
    busctl call xyz.openbmc_project.MCTP /xyz/openbmc_project/mctp/1/${eid} au.com.CodeConstruct.MCTP.Endpoint Remove
fi

