#!/bin/bash
set -e

version=$(fw-util cb --version cb_cpld | awk '{print $NF}')
echo "CB CPLD version: $version"

busctl set-property \
    xyz.openbmc_project.Settings \
    /xyz/openbmc_project/software/chassis/Minerva_CB_cb_cpld \
    xyz.openbmc_project.Software.Version \
    Version "s" "$version"
