#!/bin/bash
set -e

version=$(fw-util mb --version mb_cpld | awk '{print $NF}')
echo "MB CPLD version: $version"

busctl set-property \
    xyz.openbmc_project.Settings \
    /xyz/openbmc_project/software/chassis/Harma_MB_mb_cpld \
    xyz.openbmc_project.Software.Version \
    Version "s" "$version"
