#!/bin/bash
set -e

max_retry_count=90
retry_delay_sec=10

declare -A components=(
  ["retimer0"]="Harma_MB_retimer0"
  ["retimer1"]="Harma_MB_retimer1"
)

for component in "${!components[@]}"; do
  version=""
  for ((i=1; i<=max_retry_count; i++)); do
    version=$(fw-util mb --version "$component")
    if [ -z "$version" ] || [[ "$version" == *"NA"* ]]; then
      echo "failed to get $component version, retry after ${retry_delay_sec} seconds (count: ${i})"
      sleep "$retry_delay_sec"
    else
      break
    fi
  done

  version=$(echo "$version" | awk '{print $NF}')
  echo "$component version: $version"

  busctl set-property \
    xyz.openbmc_project.Settings \
    /xyz/openbmc_project/software/chassis/"${components[$component]}" \
    xyz.openbmc_project.Software.Version \
    Version "s" "$version"
done