#!/bin/bash
set -e

declare -A components=(
  ["cpu0_pvdd11"]="Harma_MB_vr_cpu0_pvdd11"
  ["cpu0_vcore0"]="Harma_MB_vr_cpu0_vcore0"
  ["cpu0_vcore1"]="Harma_MB_vr_cpu0_vcore1"
)

for component in "${!components[@]}"; do
  version=$(fw-util mb --version "$component" | sed -n 's/^[^:]*: //p')
  echo "$component version: $version"
  
  busctl set-property \
    xyz.openbmc_project.Settings \
    /xyz/openbmc_project/software/chassis/"${components[$component]}" \
    xyz.openbmc_project.Software.Version \
    Version "s" "$version"
done
