#!/bin/bash
set -e

max_retry_count=60
retry_delay_sec=3

version=""
for ((i=1; i<=max_retry_count; i++)); do
    version=$(fw-util nic0 --version nic0)
    if [ -z "$version" ]; then
        echo "failed to get version, retry after ${retry_delay_sec} seconds (count: ${i})"
        sleep "$retry_delay_sec"
    else
        break
    fi
done

version=$(echo "$version" | awk '{print $NF}')
echo "version: $version"

busctl set-property \
    xyz.openbmc_project.Settings \
    /xyz/openbmc_project/software/chassis/Nic_nic0 \
    xyz.openbmc_project.Software.Version \
    Version "s" "$version"