#!/bin/bash
set -e

version=$(fw-util scm --version scm_cpld | awk '{print $NF}')
echo "SCM CPLD version: $version"

busctl set-property \
    xyz.openbmc_project.Settings \
    /xyz/openbmc_project/software/chassis/Harma_SCM_scm_cpld \
    xyz.openbmc_project.Software.Version \
    Version "s" "$version"
